### PR TITLE
An on the fly shooting command that actually makes it possible to work - to be tested

### PR DESCRIPTION
**Pull request by aaditsangvikar**

### CODE REVIEW

**Comment by TotalTaxAmount** [comment]
Does this remove the need for [AutoRotateToSpeakerAndShoot.java](https://github.com/fairviewrobotics/2024-robot-code/blob/main/src/main/java/frc/robot/commands/AutoRotateToSpeakerAndShoot.java) and that one part in IndexerCommand.java?

**Comment by aaditsangvikar** [comment]
It removes the need for both RotateToSpeakerAndDriveCommand.java and IndexerCommand.java. IndexerCommand.java has this under case SPEAKER, and also has an unused case AMP, so the entire command can be removed.

**Comment by aaditsangvikar** [comment]
The AutoRotateToSpeakerAndShoot is for autonomous, but we don't use it, so I'm not sure we need it, though we may use it to tune autos later.

**Comment by TotalTaxAmount** [comment]
ah ok

**Pull request merged**
